# Generated by Django 4.2.7 on 2025-10-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
