# Generated by Django 4.2.7 on 2025-10-29 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='main_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_for', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggested_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_courses', to='myapp.course'),
        ),
    ]
