# Generated by Django 4.2.7 on 2025-10-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_suggestion_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='slug',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='myapp.course', unique=True),
        ),
    ]
