# Generated by Django 4.2.7 on 2025-10-29 09:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_suggestion_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suggestion",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="suggestion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
                migrations.AddField(
            model_name='suggestion',
            name='main_course',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='suggestions_for',
                to='myapp.course',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggested_course',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='suggested_courses',
                to='myapp.course',
            ),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="suggestion",
            unique_together={("main_course", "suggested_course")},
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="course",
        ),
    ]
