# Generated by Django 4.2.7 on 2025-10-29 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_suggestion_options_suggestion_created_at_and_more'),
    ]

    operations = [
        #         migrations.AddField(
        #     model_name='suggestion',
        #     name='main_course',
        #     field=models.ForeignKey(
        #         null=True,
        #         blank=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name='suggestions_for',
        #         to='myapp.course',
        #     ),
        # ),
        # migrations.AddField(
        #     model_name='suggestion',
        #     name='suggested_course',
        #     field=models.ForeignKey(
        #         null=True,
        #         blank=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name='suggested_courses',
        #         to='myapp.course',
        #     ),
        # ),

    ]
