# Generated by Django 5.2.8 on 2025-11-10 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='short_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='myapp.course'),
        ),
        migrations.CreateModel(
            name='SuggestedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggestedcourse', to='myapp.course')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
