# Generated by Django 5.2.4 on 2025-08-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_course_detail_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_detail',
        ),
    ]
