# Generated by Django 5.2.4 on 2025-08-14 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_course_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier for the course.', unique=True)),
                ('instructor_bio', models.TextField(blank=True, help_text='Short bio of the instructor.')),
                ('short_description', models.CharField(help_text='One-line course summary.', max_length=300)),
                ('description', models.TextField(help_text='Full course description.')),
                ('learning_outcomes', models.TextField(help_text='List what students will learn.')),
                ('requirements', models.TextField(blank=True, help_text='Prerequisites for taking this course.')),
                ('language', models.CharField(default='English', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(default='courses/images/default.png', upload_to='courses/images/')),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='courses/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructed_courses', to='myapp.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
