# Generated by Django 5.2.4 on 2025-08-14 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_course_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_detail',
            options={'ordering': ['-course__created_at']},
        ),
        migrations.RemoveField(
            model_name='course_detail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course_detail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course_detail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course_detail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course_detail',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='course_detail',
            name='title',
        ),
        migrations.AddField(
            model_name='course_detail',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.course'),
        ),
    ]
