# Generated by Django 5.2.4 on 2025-08-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_course_detail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='instructor',
            field=models.CharField(blank=True, help_text='Name of the instructor', max_length=255, null=True),
        ),
    ]
