# Generated by Django 5.2.4 on 2025-08-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_coursecategory_courselevel_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course_detail',
            name='learning_outcomes',
        ),
        migrations.RemoveField(
            model_name='course_detail',
            name='requirements',
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_detail',
            name='certificate',
            field=models.CharField(blank=True, help_text='Certificate type (e.g. Shareable).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_detail',
            name='exercises_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of practice exercises.'),
        ),
        migrations.AddField(
            model_name='course_detail',
            name='languages_available',
            field=models.CharField(blank=True, help_text='Languages supported.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_detail',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_detail',
            name='outcomes',
            field=models.TextField(blank=True, help_text='What students will learn (comma-separated).'),
        ),
        migrations.AddField(
            model_name='course_detail',
            name='overview',
            field=models.TextField(blank=True, help_text='Detailed course overview.', null=True),
        ),
        migrations.AddField(
            model_name='course_detail',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills gained (comma-separated).'),
        ),
        migrations.AddField(
            model_name='course_detail',
            name='tools',
            field=models.TextField(blank=True, help_text='Tools covered (comma-separated).'),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.DeleteModel(
            name='CourseLevel',
        ),
        migrations.DeleteModel(
            name='CourseReview',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
