# Generated by Django 4.2.7 on 2025-10-15 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_suggestion_courses_remove_suggestion_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='myapp.course'),
        ),
    ]
