# Generated by Django 5.2.4 on 2025-08-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_course_category_remove_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='exercises_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='instructor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='instructor_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='languages_available',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='short_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
