# Generated by Django 5.2.4 on 2025-08-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_course_detail_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='overview',
            field=models.TextField(blank=True, default='default'),
        ),
    ]
