# Generated by Django 5.2.4 on 2025-08-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_course_detail_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='overview',
            field=models.TextField(blank=True, default=list),
        ),
    ]
