# Generated by Django 4.2.7 on 2025-10-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_course_detail_short_description_and_more'),
        ('myapp', '0013_alter_suggestion_main_course_and_more'),
    ]

    operations = [
    ]
