# Generated by Django 5.2.4 on 2025-08-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_course_detail_overview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_detail',
            options={},
        ),
        migrations.RemoveField(
            model_name='course_detail',
            name='preview_video',
        ),
        migrations.AddField(
            model_name='course_detail',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='outcomes',
            field=models.TextField(blank=True, help_text='One outcome per line'),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='skills',
            field=models.TextField(blank=True, help_text='One skill per line'),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='tools',
            field=models.TextField(blank=True, help_text='One tool per line'),
        ),
    ]
