# Generated by Django 5.2.4 on 2025-08-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_course_detail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='/home/dhruvin-dave/learnapp/static/images/default_z9GfW7G.png', null=True, upload_to='static/images/'),
        ),
    ]
