# Generated by Django 5.2.4 on 2025-08-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='static/images/default.png', upload_to='static/images/'),
        ),
    ]
